# Generated by Django 4.1.1 on 2022-10-25 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.place')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.topic')),
            ],
        ),
    ]
